In [1]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("./house_price1.csv")

In [6]:
df

town  area   price
0   monroetownship  2600  550000
1   monroetownship  3000  565000
2   monroetownship  3200  610000
3   monroetownship  3600  680000
4   monroetownship  4000  725000
5      westwindsor  2600  585000
6      westwindsor  2800  615000
7      westwindsor  3300  650000
8      westwindsor  3600  710000
9     robbinsville  2600  575000
10    robbinsville  2900  600000
11    robbinsville  3100  620000
12    robbinsville  3600  695000

In [9]:
dummies = pd.get_dummies(df.town)

In [10]:
dummies

monroetownship  robbinsville  westwindsor
0                1             0            0
1                1             0            0
2                1             0            0
3                1             0            0
4                1             0            0
5                0             0            1
6                0             0            1
7                0             0            1
8                0             0            1
9                0             1            0
10               0             1            0
11               0             1            0
12               0             1            0

In [11]:
merged = pd.concat([df,dummies],axis='columns')
merged

town  area   price  monroetownship  robbinsville  westwindsor
0   monroetownship  2600  550000               1             0            0
1   monroetownship  3000  565000               1             0            0
2   monroetownship  3200  610000               1             0            0
3   monroetownship  3600  680000               1             0            0
4   monroetownship  4000  725000               1             0            0
5      westwindsor  2600  585000               0             0            1
6      westwindsor  2800  615000               0             0            1
7      westwindsor  3300  650000               0             0            1
8      westwindsor  3600  710000               0             0            1
9     robbinsville  2600  575000               0             1            0
10    robbinsville  2900  600000               0             1            0
11    robbinsville  3100  620000               0             1            0
12    robbinsville  3600  695000               0             1            0

In [12]:
final = merged.drop(['town','westwindsor'], axis='columns')

In [13]:
final

area   price  monroetownship  robbinsville
0   2600  550000               1             0
1   3000  565000               1             0
2   3200  610000               1             0
3   3600  680000               1             0
4   4000  725000               1             0
5   2600  585000               0             0
6   2800  615000               0             0
7   3300  650000               0             0
8   3600  710000               0             0
9   2600  575000               0             1
10  2900  600000               0             1
11  3100  620000               0             1
12  3600  695000               0             1

In [14]:
from sklearn import linear_model

In [15]:
model = linear_model.LinearRegression()

In [16]:
x = final.drop('price', axis='columns')

In [17]:
x

area  monroetownship  robbinsville
0   2600               1             0
1   3000               1             0
2   3200               1             0
3   3600               1             0
4   4000               1             0
5   2600               0             0
6   2800               0             0
7   3300               0             0
8   3600               0             0
9   2600               0             1
10  2900               0             1
11  3100               0             1
12  3600               0             1

In [18]:
y = final.price

In [19]:
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [20]:
model.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [22]:
model.predict([[2800,0,1]])

array([590775.63964739])

In [23]:
model.predict([[3400,0,0]])

array([681241.66845839])

In [24]:
model.score(x,y)

0.9573929037221873

In [25]:
df

town  area   price
0   monroetownship  2600  550000
1   monroetownship  3000  565000
2   monroetownship  3200  610000
3   monroetownship  3600  680000
4   monroetownship  4000  725000
5      westwindsor  2600  585000
6      westwindsor  2800  615000
7      westwindsor  3300  650000
8      westwindsor  3600  710000
9     robbinsville  2600  575000
10    robbinsville  2900  600000
11    robbinsville  3100  620000
12    robbinsville  3600  695000

In [26]:
from sklearn.preprocessing import LabelEncoder

In [27]:
le = LabelEncoder()

In [28]:
dfle = df

In [29]:
le.fit_transform(dfle.town)

array([0, 0, 0, 0, 0, 2, 2, 2, 2, 1, 1, 1, 1])

In [30]:
dfle.town = le.fit_transform(dfle.town)

In [31]:
dfle

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [34]:
x = dfle[['town','area']].values

In [35]:
x

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]], dtype=int64)

In [36]:
y= dfle.price

In [37]:
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [41]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(categorical_features=[0])

In [43]:
x = ohe.fit_transform(x).toarray()

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [44]:
x

array([[0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 3.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 4.0e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 2.8e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 3.3e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 3.6e+03]])

In [46]:
x = x[:,1:]

In [47]:
x

array([[1.0e+00, 0.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.0e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.2e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.9e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.1e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.6e+03]])

In [48]:
model.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [51]:
model.predict([[1,0,2800]])

ValueError: shapes (1,3) and (4,) not aligned: 3 (dim 1) != 4 (dim 0)