In [1]:
# y = m1x1 + m2x2 + m3+x3 +b
# where m1,m2,m3 are co-efficient
#        b is the intercept
#         x1,x2,x3 are independent varible and
#         y is the dependent variable

In [3]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [4]:
df = pd.read_csv("./home_prices.csv")

In [5]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [6]:
df.bedrooms

0    3.0
1    4.0
2    NaN
3    3.0
4    5.0
Name: bedrooms, dtype: float64

In [8]:
df.bedrooms.median()

3.5

In [9]:
import math
median_bedrooms = math.floor(df.bedrooms.median())

In [10]:
median_bedrooms

3

In [11]:
df.bedrooms.fillna(median_bedrooms)

0    3.0
1    4.0
2    3.0
3    3.0
4    5.0
Name: bedrooms, dtype: float64

In [12]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)

In [13]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [14]:
reg = linear_model.LinearRegression()

In [15]:
reg.fit(df[['area','bedrooms','age']],df['price'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [17]:
reg.predict([[3000,3,40]])

array([444400.])

In [21]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [19]:
reg.intercept_

383724.9999999998

In [22]:
# y = m1x1 + m2x2 + m3+x3 +b

In [24]:
m1=reg.coef_[0]
m2=reg.coef_[1]
m3=reg.coef_[2]
print(m1,m2,m3)

137.25000000000003 -26024.999999999996 -6824.999999999997


In [26]:
b = reg.intercept_
b

383724.9999999998

In [27]:
y = m1*3000 + m2*3 + m3*40 + b

In [28]:
y

444400.0

In [29]:
reg.predict([[2500,4,5]])

array([588625.])